version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
    ignore:
      - dependency-name: "chalk"
        versions: [">=5.0.0"]