name: test the code
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      INVIDIOUS_TOKEN: ${{ secrets.INVIDIOUS_TOKEN }}
      INVIDIOUS_INSTANCE: ${{ secrets.INVIDIOUS_INSTANCE }}
    steps:
      - name: 🚧 Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Start mock Invidious server
        run: |
          node .github/test/mock-invidious.js &
          sleep 3 # wait for server to start
      - name: Create dummy freetube files
        run: |
          mkdir -p ./dummy-ft
          # copy the dummy files from the test directory
          # this is to ensure that the export script doesn't fail due to missing files
          cp .github/test/*.db ./dummy-ft/
          mkdir -p ./exports
          # assurance
          for f in history.db playlists.db profiles.db; do
          test -f dummy-ft/$f || (echo "❌ Missing dummy-ft/$f" && exit 1)
          done
          sleep 1
      - name: Run Invidious sync
        run: |
          node export.js --token=${{ secrets.INVIDIOUS_TOKEN }} -i http://localhost:9999 --freetube-dir=dummy-ft/  -v --dont-run-setup --export-dir=./exports --insecure