# .github/workflows/invidious-sync.yml
name: test the code
# make sure it isn't complete garbage
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      INVIDIOUS_TOKEN: ${{ secrets.INVIDIOUS_TOKEN }}
      INVIDIOUS_INSTANCE: ${{ secrets.INVIDIOUS_INSTANCE }}
    steps:
      - name: 🚧 Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      - name: Create dummy freetube files
        run: |
          mkdir -p ./dummy-ft
          # using actual entries here because that's what the exporter expects
          echo '{"videoId":"QZfH7cFp3Ys","title":"Twenty One Pilots - The Contract (Official Video)","author":"twenty one pilots","authorId":"UCBQZwaNPFfJ1gZ1fLZpAEGw","published":1749686400000,"description":"","viewCount":12400951,"lengthSeconds":265,"watchProgress":264.541,"timeWatched":1752798414477,"isLive":false,"type":"video","_id":"MmsHIe3eWuHsjhSy"}' > dummy-ft/history.db
          echo '{"_id":"allChannels","name":"Profile.All Channels","bgColor":"#9d0006","textColor":"#FFFFFF","subscriptions":[{"id":"UCBS1NUWY7oC6FFHaXQy4zAA","name":"Zach's Tech Turf","thumbnail":"https://yt3.ggpht.com/u_qUyuvPxysFAlmVypBaTtXFYW81vbWMAWl0xxjo-K1kP34KEIXj69iOn6ZqoYFBZWPIpEy-bg=s176-c-k-c0x00ffffff-no-rj"},{"id":"UCdBK94H6oZT2Q7l0-b0xmMg","name":"ShortCircuit","thumbnail":"https://yt3.ggpht.com/ytc/AIdro_mDZiWSYXmBc_fiS3QG-Uh5mJRdww9Z-2qUDeXtMZhGTQ=s176-c-k-c0x00ffffff-no-rj"}]}' > dummy-ft/profiles.db
          echo '{"playlistName":"a playlist","description":"","videos":[{"videoId":"QZfH7cFp3Ys","title":"Twenty One Pilots - The Contract (Official Video)","author":"twenty one pilots","authorId":"UCBQZwaNPFfJ1gZ1fLZpAEGw","lengthSeconds":265,"published":1749744071000,"timeAdded":1750918794381,"playlistItemId":"341b9933-59d3-45af-8802-e4b0b11e3246","type":"video"}]}' > dummy-ft/playlists.db
          mkdir -p ./exports
          
          for f in history.db playlists.db profiles.db; do
          test -f dummy-ft/$f || (echo "❌ Missing dummy-ft/$f" && exit 1)
          done
      - name: Run Invidious sync
        run: |
          node export.js  --token=${{ secrets.INVIDIOUS_TOKEN }} --instance=${{ secrets.INVIDIOUS_INSTANCE }} --freetube-dir=dummy-ft/  -v --dont-run-setup --export-dir=./exports
          # one line because node doesn't like multiline commands